backend:
  - changed-files:
      - any-glob-to:
          - 'backend/**'
          - 'venv/pyvenv.cfg'
          - '.python-version'

frontend:
  - changed-files:
      - any-glob-to:
          - 'frontend/**'
          - 'package.json'
          - 'package-lock.json'

docs:
  - changed-files:
      - any-glob-to:
          - 'docs/**'
          - '**/*.md'
          - 'README.md'

infra:
  - changed-files:
      - any-glob-to:
          - 'infra/**'
          - '.github/workflows/**'
          - 'vercel.json'
          - 'Makefile'

dependencies:
  - changed-files:
      - any-glob-to:
          - '**/requirements.txt'
          - '**/package.json'
          - '**/package-lock.json'
          - '**/Pipfile'
          - '**/poetry.lock'

